### PR TITLE
fix: update to use low level zero_length_array

### PR DESCRIPTION
**Pull request by lgray**
Address deprecation warning in awkward 2.2.0

### CODE REVIEW

**Comment by lgray** [comment]
The failure in these tests appears to be a strange interaction between dask_awkward optimization and dask_array blockwise functions. @martindurant

**Comment by martindurant** [comment]
Should pass after merge from main?

**Comment by lgray** [comment]
How? CI needs a new release to pull the package with the improvement.

**Comment by martindurant** [comment]
Ah sorry, wrong repo :|

**Pull request merged**
