### PR TITLE
fix: dask_histogram.factory broken after dask 2024.12

### LINKED ISSUE #155: Regression in use with dask-awkward
```python
import boost_histogram as bh
import dask_awkward as dak
import dask_histogram as dh

arr = dak.from_lists([list(range(10))] * 3)
axis = bh.axis.Regular(10, 0., 10.)
hist = dh.factory(
    arr,
    axes=(axis,),
).compute()
print(hist.values())
```

Works on dask 2024.11.2, distributed 2024.11.2 and dask-awkward 2024.9.0:
```output
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
```

Broken with dask 2024.12.0, distributed 2024.12.0 and dask-awkward 2024.12.1:
```python
Traceback (most recent call last):
  File "/tmp/regr/regr.py", line 10, in <module>
    ).compute()
      ^^^^^^^^^
  File "/nix/store/nbqgvfbciwpxdazx5zn72i31wckkp5ad-python3.12-dask-2024.12.0/lib/python3.12/site-packages/dask/base.py", line 372, in compute
    (result,) = compute(self, traverse=False, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/nbqgvfbciwpxdazx5zn72i31wckkp5ad-python3.12-dask-2024.12.0/lib/python3.12/site-packages/dask/base.py", line 660, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9x4i6b87rx9w6y26732msn50rnn6fbr8-python3.12-dask-histogram-2024.9.1/lib/python3.12/site-packages/dask_histogram/core.py", line 290, in _blocked_dak
    return thehist.fill(thedata, weight=theweights, sample=thesample)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/3h45q4z2cg38204ja42696kbik3j2wxb-python3.12-boost-histogram-1.5.0/lib/python3.12/site-packages/boost_histogram/_internal/hist.py", line 511, in fill
    self._hist.fill(*args_ars, weight=weight_ars, sample=sample_ars)  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Wrong number of args
```

### PR DESCRIPTION
**Pull request by lgray**
Fixes #155

### CODE REVIEW

**Comment by lgray** [comment]
just adding a test for now

**Comment by douglasdavis** [comment]
I don't think it's associated with `Delayed` this time. I think the issue is in `_partitioned_histogram`. The `None`'s getting passed to dask-awkward's partitionwise need to be `Alias` or `TaskRef`

**Comment by lgray** [comment]
I'll check it out in the morning. Not feeling like dealing with a partially documented and changing interface at the moment.

**Comment by lgray** [comment]
But thank you for the pointers!

**Comment by douglasdavis** [comment]
No worries :) this may help; it gets the test to pass:
```diff
diff --git a/src/dask_histogram/core.py b/src/dask_histogram/core.py
index b80943d..b63823a 100644
--- a/src/dask_histogram/core.py
+++ b/src/dask_histogram/core.py
@@ -1026,6 +1026,7 @@ def _partitioned_histogram(
     # Single awkward array object.
     if len(data) == 1 and data_is_dak:
         from dask_awkward.lib.core import partitionwise_layer as dak_pwl
+        from dask_awkward.layers import _dask_uses_tasks
 
         x = data[0]
         if weights is not None and sample is not None:
@@ -1035,7 +1036,9 @@ def _partitioned_histogram(
         elif weights is None and sample is not None:
             g = dak_pwl(_blocked_dak, name, x, None, sample, histref=histref)
         else:
-            g = dak_pwl(_blocked_dak, name, x, None, None, histref=histref)
+            import functools
+            ff = functools.partial(_blocked_dak, weights=None, sample=None, histref=histref)
+            g = dak_pwl(ff, name, x)
 
     # Single object, not a dataframe
     elif len(data) == 1 and not data_is_df:
```

**Comment by douglasdavis** [comment]
These tests are failing locally for me:
```
================================================================================= short test summary info =================================================================================
FAILED tests/test_boost.py::test_histogramdd_series - KeyError: '.0'
FAILED tests/test_boost.py::test_histogramdd_arrays_and_series - ValueError: spans must have compatible lengths
FAILED tests/test_boost.py::test_histogramdd_dataframe - ValueError: spans must have compatible lengths
FAILED tests/test_core.py::test_df_input[True] - ValueError: spans must have compatible lengths
FAILED tests/test_core.py::test_df_input[None] - KeyError: '.0'
======================================================================== 5 failed, 81 passed, 2 warnings in 2.90s =========================================================================
```
All have to do with dask.dataframe. Probably _those_ are related to the Task spec. @lgray if you're OK with it I'd say this is fine to go in to fix the original issue. dask.dataframe things can be dealt with in another PR.

**Comment by lgray** [comment]
Thanks! My only nit here is that dak.partitionwise_layer should be taking care of these cases correctly, no? So I think the right way to fix it would be to use TaskRef correctly over in dask-awkward?

**Comment by lgray** [comment]
or is this sort-of-currying the function fine? it seems like a requirement on dependent code.

**Comment by lgray** [comment]
will merge for now - we'll see if this nitpick crops up later.

**Comment by douglasdavis** [comment]
Yeah I think the dak partitionwise layer should be able to handle "broadcasting" the None for all partitions of the actual data-carrying collection. I think in the past Dask was doing this correctly itself, but clearly they've changed things in blockwise.

For now we're just creating a higher order function to make sure a None gets used at each node as part of the callable instead of as an argument... the more I think about it the cleaner it seems.

**Pull request merged**
