### PR TITLE
[fix]Solve circular import

### LINKED ISSUE #149: Cannot `import dask_histogram` which causes failures downstream (`hist.dask` etc) with the newest `dask 2024.9.0`
```python
In [1]: import dask_histogram
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import dask_histogram

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask_histogram/__init__.py:1
----> 1 from dask_histogram import config  # isort:skip; load dask-histogram config
      3 import boost_histogram.axis as _axis
      4 import boost_histogram.storage as _storage

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask_histogram/config.py:3
      1 import os
----> 3 import dask.config
      4 import yaml
      6 config = dask.config.config

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask/__init__.py:5
      3 from dask import config, datasets
      4 from dask._version import get_versions
----> 5 from dask.base import (
      6     annotate,
      7     compute,
      8     get_annotations,
      9     is_dask_collection,
     10     optimize,
     11     persist,
     12     visualize,
     13 )
     14 from dask.core import istask
     15 from dask.delayed import delayed

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask/base.py:1039
   1030     from dask import threaded
   1032     named_schedulers.update(
   1033         {
   1034             "threads": threaded.get,
   1035             "threading": threaded.get,
   1036         }
   1037     )
-> 1039     from dask import multiprocessing as dask_multiprocessing
   1041     named_schedulers.update(
   1042         {
   1043             "processes": dask_multiprocessing.get,
   1044             "multiprocessing": dask_multiprocessing.get,
   1045         }
   1046     )
   1049 get_err_msg = """
   1050 The get= keyword has been removed.
   1051
   (...)
   1065     x.compute(scheduler=client)
   1066 """.strip()

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask/multiprocessing.py:19
     17 from dask import config
     18 from dask.local import MultiprocessingPoolExecutor, get_async, reraise
---> 19 from dask.optimization import cull, fuse
     20 from dask.system import CPU_COUNT
     21 from dask.typing import Key

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask/optimization.py:10
      7 from typing import Any
      9 from dask import config, core, utils
---> 10 from dask._task_spec import GraphNode
     11 from dask.base import normalize_token, tokenize
     12 from dask.core import (
     13     flatten,
     14     get_dependencies,
   (...)
     19     toposort,
     20 )

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask/_task_spec.py:90
     88 from dask.base import tokenize
     89 from dask.core import reverse_dict
---> 90 from dask.sizeof import sizeof
     91 from dask.typing import Key as KeyType
     92 from dask.utils import is_namedtuple_instance

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask/sizeof.py:318
    312         except Exception:
    313             logger.exception(
    314                 f"Failed to register sizeof entry point {entry_point.name}"
    315             )
--> 318 _register_entry_point_plugins()

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask/sizeof.py:309, in _register_entry_point_plugins()
    307 """Register sizeof implementations exposed by the entry_point mechanism."""
    308 for entry_point in importlib_metadata.entry_points(group="dask.sizeof"):
--> 309     registrar = entry_point.load()
    310     try:
    311         registrar(sizeof)

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/importlib_metadata/__init__.py:189, in EntryPoint.load(self)
    184 """Load the entry point from its definition. If only a module
    185 is indicated by the value, return that module. Otherwise,
    186 return the named object.
    187 """
    188 match = cast(Match, self.pattern.match(self.value))
--> 189 module = import_module(match.group('module'))
    190 attrs = filter(None, (match.group('attr') or '').split('.'))
    191 return functools.reduce(getattr, attrs, module)

File ~/miniforge3/envs/egamma_dev/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask_awkward/__init__.py:3
      1 from dask_awkward import config  # isort:skip; load awkward config
----> 3 import dask_awkward.lib.core as core
      4 import dask_awkward.lib.describe as describe
      5 import dask_awkward.lib.inspect as inspect

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask_awkward/lib/__init__.py:1
----> 1 import dask_awkward.lib.str as str
      2 import dask_awkward.lib.utils as utils
      3 from dask_awkward.lib.core import Array, PartitionCompatibility, Record, Scalar

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask_awkward/lib/str.py:10
      7 import awkward.operations.str as akstr
      8 from typing_extensions import ParamSpec
---> 10 from dask_awkward.lib.core import Array, map_partitions
     12 T = TypeVar("T")
     13 P = ParamSpec("P")

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask_awkward/lib/core.py:38
     24 from awkward.typetracer import (
     25     MaybeNone,
     26     OneOf,
   (...)
     29     is_unknown_scalar,
     30 )
     31 from dask.base import (
     32     DaskMethodsMixin,
     33     dont_optimize,
   (...)
     36     unpack_collections,
     37 )
---> 38 from dask.blockwise import BlockwiseDep
     39 from dask.blockwise import blockwise as dask_blockwise
     40 from dask.context import globalmethod

File ~/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask/blockwise.py:13
     10 import tlz as toolz
     12 import dask
---> 13 from dask.base import clone_key, get_name_from_key, tokenize
     14 from dask.core import flatten, ishashable, keys_in_tasks, reverse_dict
     15 from dask.highlevelgraph import HighLevelGraph, Layer

ImportError: cannot import name 'clone_key' from partially initialized module 'dask.base' (most likely due to a circular import) (/Users/iason/miniforge3/envs/egamma_dev/lib/python3.10/site-packages/dask/base.py)
```

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #149 

This is a more complex way of solving things, by splitting this into two packages.

### CODE REVIEW

**Comment by lgray** [comment]
Hmmm still brings up the same problem :-/

**Comment by martindurant** [comment]
These fail because they use the released version of dask-awkward

**Comment by lgray** [comment]
indeed - I should look at these things after coffee.

Otherwise lgtm.

**Comment by martindurant** [comment]
OK, release is out on pypi and things are importable again.

**Comment by lgray** [comment]
Something's gone off with with the tests and optimization. One of the awkward histogram filling tests should be using the optimization function from dask awkward as opposed to dask histogram and now it has stopped doing that.

**Comment by martindurant** [comment]
I don't understand. This is a new issue? No code changed here...

**Comment by lgray** [comment]
Yeah I am not sure, but tests in main are failing.

I'll check on my laptop in a bit.

**Comment by lgray** [comment]
The tests even passed in your PR so that's rather strange!

**Comment by martindurant** [comment]
https://github.com/dask-contrib/dask-histogram/actions/runs/10946251458/job/30392316434?pr=152#step:5:138 you seem to be right. I have it locally too, must have been a different commit, though.

**Comment by martindurant** [comment]
OK, so the case is: dask is no longer auto-importing dask-awkward as before. If you import dask-awkward before running the graph, it is right.
This was the point! dask-histogram uses the existence of "awkward" in the dask config to see whether dak has been imported, and then sets the optimise method. We can use importlib instead.

**Comment by martindurant** [comment]
```diff
--- a/src/dask_histogram/core.py
+++ b/src/dask_histogram/core.py
@@ -524,7 +524,9 @@ def _get_optimization_function():
     # running this optimization even in cases where it's unncessary
     # because if no AwkwardInputLayers from dask-awkward are
     # detected then the original graph is returned unchanged.
-    if dask.config.get("awkward", default=False):
+    import importlib.metadata
+
+    if importlib.metadata.distribution("dask_awkward"):
         from dask_awkward.lib.optimize import all_optimizations
```

OK?

**Pull request merged**
